FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . . 
RUN dotnet restore "PlayCodeApi.SwaggerDemo/PlayCodeApi.SwaggerDemo.csproj"
WORKDIR /src/PlayCodeApi.SwaggerDemo
RUN dotnet build "PlayCodeApi.SwaggerDemo.csproj" -c Release -o /app

FROM build AS publish
WORKDIR /src/PlayCodeApi.SwaggerDemo
RUN dotnet publish "PlayCodeApi.SwaggerDemo.csproj" -c Release -o /app /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "PlayCodeApi.SwaggerDemo.dll"]
